--- # condition ansible playbook
- hosts: demo
  user: ansible
  become: yes
  connection: ssh

  tasks:
       - name: Apache Install Debian
         command: apt-get install apache2 -y
         when: ansible_os_family=="Debian"
       - name: Apache Install RedHat
         command: yum install httpd -y
         when: ansible_os_family=="RedHat"