--- # ansible handler example
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
   - name: Install latest version of Apache
     yum:
      name: httpd
      state: latest
     notify:
      - start apache
  handlers:
     - name: start apache
       service:
         name: httpd
         state: started