apiVersion: v1
kind: Pod
metadata:
  name: myvolhostpath
spec:
  containers:
  - image: centos
    name: testc
    command: ["/bin/bash", "-c", "sleep 15000"]
    volumeMounts:
    - mountPath: /tmp/hostpath
      name: testdemo
  volumes:
  - name: testdemo
    hostPath:
      path: "/var/lib/docker/volumes/testdemo/_data"