kind: ReplicaSet                                    
apiVersion: apps/v1                            
metadata:
  name: myreplicaset
spec:
  replicas: 4  
  selector:                  
    matchExpressions:                             # these must match the labels
      - {key: myname, operator: In, values: [Bunty, BuntyMhatre, BuntyBhai]}
      - {key: env, operator: NotIn, values: [production]}
  template:      
    metadata:
      name: testpod7
      labels:              
        myname: BuntyBhai
    spec:
     containers:
       - name: c00
         image: ubuntu
         #command: ["/bin/bash", "-c", "while true; do echo Hello BuntyBhai; sleep 5 ; done"]
