kind: Pod
apiVersion: v1
metadata:
  name: environments
  labels:
    envirnment: Development_Southstar
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Jaydip the leader; sleep 5 ; done"]
