kind: ReplicationController               
apiVersion: v1
metadata:
  name: myreplica
  annotations:
    description: Creating ReplicationController pods
spec:
  replicas: 3            
  selector:        
    myname: Jaydip                             
  template:                
    metadata:
      name: replicajaydipmhatrepod
      labels:            
        myname: Jaydip
    spec:
     containers:
       - name: c00
         image: ubuntu
         #command: ["/bin/bash", "-c", "while true; do echo This is replica pods; sleep 5 ; done"]
      
