apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-secrets-1
  namespace: sre
roleRef: # points to my ClusterRole
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring
subjects: # points to my ServiceAccount
- kind: ServiceAccount
  name: srejaydip
  namespace: sre
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-secrets-2
  namespace: argocd
roleRef: # points to my ClusterRole
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring
subjects: # points to my ServiceAccount
- kind: ServiceAccount
  name: srejaydip
  namespace: sre