---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app-abhi
  labels:
    app: tomcat-app-support-oc
  namespace: abhi-java-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-app-abhi
  template:
    metadata:
      labels:
        app: tomcat-app-abhi
    spec:
      #serviceAccountName: view-serviceaccount
      #progressDeadlineSeconds: 600
      containers:
      - name: tomcat-app-abhi
        #image: docker.io/abhimanyubajaj98/java-tomcat-sample-app-buildx:latest
        image: docker.io/abhimanyubajaj98/java-application:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_TOOL_OPTIONS
          value: -Xmx512m
        - name: APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX
          valueFrom:
           fieldRef: 
             fieldPath: metadata.name
        #- name: APPDYNAMICS_AGENT_UNIQUE_HOST_ID
        #  value: $(cat /proc/self/cgroup | head -1 | awk -F '/' '{print $NF}' | cut -c 16-27)
        #startupProbe:
        #    httpGet:
        #      path: /sampletest/
        #      port: 8080
        #    initialDelaySeconds: 20
        #readinessProbe:
        #    httpGet:
        #      path: /sampletest/
        #      port: 8080
        #    initialDelaySeconds: 30
        #    periodSeconds: 10
        #livenessProbe:
        #    httpGet:
        #      path: /sampletest/
        #      port: 8080
        #    initialDelaySeconds: 60
        #    periodSeconds: 15
        #    failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-app-service
  labels:
    app: tomcat-app-abhi
  namespace: abhi-java-apps
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: tomcat-app-abhi
